-- Add migration script here
CREATE TABLE IF NOT EXISTS events
(
	id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name       VARCHAR(255) NOT NULL UNIQUE,
	active     BOOLEAN NOT NULL DEFAULT false,
	archive    BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON events (active)
WHERE active = true;

CREATE TABLE IF NOT EXISTS events_scenarios
(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id BIGINT,
	scenario_id BIGINT,
	complete BOOLEAN DEFAULT false,
	checkout TIMESTAMP,
	checkout_user VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(event_id) REFERENCES events(id),
	FOREIGN KEY(scenario_id) REFERENCES scenarios(id)
);
